export const CardInput = [
  {
    id: "a",
    title: "Lakavimas",
    duration: " 20h",
    price: " 200eur",
    content:
      " FRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LASTFRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LASTFRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LASTFRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LASTFRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LASTFRIST abcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasdabcasdasdasdasd LAST",
    background: "white",
  },
  {
    id: "b",
    title: "SUDAS",
    duration: " 21h",
    price: " 201eur",
    content: "b",
    background: "white",
  },
];
