export const formData = [
  {
    id: "1",
    name: "firstName",
    placeholder: "Vardas",
    type: "text",
    element: "input",
    requirements: { required: true, minLength: 2 },
  },
  {
    id: "2",
    error: "errors.firstName",
    inputName: "varda",
    minLength: "2",
    element: "error",
  },
  {
    id: "3",
    name: "phone",
    placeholder: "Telefono Numeris",
    type: "text",
    element: "input",
    requirements: {
      pattern: /\+370[0-9]*$/,
      required: true,
      maxLength: 12,
      minLength: 12,
    },
  },
  {
    id: "4",
    error: "errors.phone",
    inputName: "telefono numeri",
    minLength: "12",
    element: "error",
  },
  { id: "5", text: "Pasirinkite procedura", element: "label" },
  {
    id: "6",
    name: "procedure",
    element: "select",
    requirements: { required: true },
  },
  {
    id: "7",
    error: "errors.procedure",
    inputName: "procedura",
    element: "error",
  },
  { id: "8", text: "Pasirinkite data ir laika", element: "label" },
  // {
  //   id: "9",
  //   name: "registrationDate",
  //   placeholder: "Pasirinkite data...",
  //   type: "text",
  //   element: "input",
  //   autoComplete: "off",
  //   requirements: { required: true },
  // },
  // {
  //   id: "10",
  //   error: "errors.registrationDate",
  //   inputName: "data",
  //   element: "error",
  // },
  {
    id: "11",
    name: "time",
    element: "select",
    requirements: { required: true },
  },
  {
    id: "12",
    error: "errors.time",
    inputName: "laika",
    element: "error",
  },
  { id: "13", type: "submit", element: "submit" },
];
